---
abstract: "By default Moo turns all warnings to fatal warnings. C<Moo::Lax> is exactly the same as C<Moo>, except that it doesn't turn all warnings to fatal warnings in the calling module."
author:
  - 'Damien Krotkine <dams@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.63_03
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moo-Lax
requires:
  Moo: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/dams/p5-Moo-Lax/issues
  homepage: https://github.com/dams/p5-Moo-Lax
  repository: https://github.com/dams/p5-Moo-Lax.git
version: 0.10
